# Generated by Django 4.0.3 on 2022-03-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QrCodeGen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=64)),
                ('price', models.PositiveIntegerField(default=0)),
                ('img', models.ImageField(upload_to='code')),
            ],
        ),
    ]
