# Generated by Django 4.0.3 on 2022-03-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodegen',
            name='img',
            field=models.ImageField(blank=True, upload_to='code'),
        ),
    ]
